FROM python:3.5-alpine

# create the folder code inside the docker image
RUN mkdir /code

# set the working directory inside the image
WORKDIR /code

# copy the fastflow executable inside the image
#COPY test_parfor_unbalanced /code/
COPY nodecontroller.py /code/

COPY requirements.txt /code/

RUN pip install -r requirements.txt

# when the container starts it runs the executable in the entrypoint

ENTRYPOINT ["python","/code/nodecontroller.py"]
