FROM python:3.5-alpine

# create the folder code inside the docker image
RUN mkdir /code

# set the working directory inside the image
WORKDIR /code

# copy the fastflow executable inside the image
#COPY test_parfor_unbalanced /code/
COPY socket_server.py /code/
COPY requirements.py /code/

RUN pip install -r requirements.py

# when the container starts it runs the executable in the entrypoint
#ENTRYPOINT ["python","/code/test_parfor_unbalance"]
ENTRYPOINT ["python","/code/socket_server.py"]
