FROM python:3.5

# create the folder code inside the docker image
RUN mkdir /code

# set the working directory inside the image
WORKDIR /code

#COPY fnc.py /code/

COPY requirements.txt /code/

RUN pip install -r requirements.txt

# when the container starts it runs the executable in the entrypoint (-u unbuffered output)
ENTRYPOINT ["python","-u", "/code/fnc.py"]
