FROM python:3.5-alpine

# create the folder code inside the docker image
RUN mkdir /code

# set the working directory inside the image
WORKDIR /code


# when the container starts it runs the executable in the entrypoint
ENTRYPOINT ["python","-u","/code/selection.py"]
