FROM python:3.5-alpine

# create the folder code inside the docker image
RUN mkdir /code

# set the working directory inside the image
WORKDIR /code

# copy the code of the parallel application inside the container.
# COPY socket_server_inet.py /


# when the container starts it runs the executable in the entrypoint
ENTRYPOINT ["python","-u","/code/socket_server_inet.py"]
