FROM python:3.5-alpine

# copy the code of the parallel application inside the container.
COPY socket_server.py /

# when the container starts it runs the executable in the entrypoint
ENTRYPOINT ["python","-u","/socket_server.py"]
